<?
$PERM["admin"]["8"]="R";
$PERM["bitrix"]["8"]="D";
$PERM["Buyer-personal-account"]["*"]="D";
$PERM["seller-personal-account"]["*"]="D";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>